# -*- coding: utf-8 -*-
"""IDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/sheetalsamaje1008-stack/9d1265dc9dabbd1b32e9e7c7549fb5c2/untitled0.ipynb
"""

def depth_limited_search(state, goal, depth, path):
    if state == goal:
        return path

    if depth == 0:
        return None

    zero = state.index(0)
    row, col = divmod(zero, 3)

    # Possible moves: Up, Down, Left, Right
    moves = []

    if row > 0:
        moves.append(zero - 3)  # Up
    if row < 2:
        moves.append(zero + 3)  # Down
    if col > 0:
        moves.append(zero - 1)  # Left
    if col < 2:
        moves.append(zero + 1)  # Right

    for new_zero in moves:
        new_state = list(state)

        # Swap empty space (0) with the neighboring tile
        new_state[zero], new_state[new_zero] = \
            new_state[new_zero], new_state[zero]

        new_state = tuple(new_state)

        # Avoid states already present in the current path
        if new_state not in path:
            result = depth_limited_search(
                new_state,
                goal,
                depth - 1,
                path + [new_state]
            )

            if result is not None:
                return result

    return None


def IDS(initial, goal):
    depth = 0

    while True:
        result = depth_limited_search(
            initial,
            goal,
            depth,
            [initial]
        )

        if result is not None:
            return result

        depth += 1


# Initial state
initial = (
    1, 2, 3,
    0, 4, 6,
    7, 5, 8
)

# Goal state
goal = (
    1, 2, 3,
    4, 5, 6,
    7, 8, 0
)

solution = IDS(initial, goal)

# Print solution
print("Solution path:")

for state in solution:
    for i in range(0, 9, 3):
        print(state[i:i+3])
    print()

